archives:
  -
    replacements:
      386: i386
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
before:
  hooks: ~
build:
  binary: http-server
  env:
    - CGO_ENABLED=1
  goarch:
    - amd64
    - arm
    - arm64
  goos:
    - linux
    - windows
    - darwin
  main: ./cmd/http-server
  skip: false
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: asc
checksum:
  name_template: checksums.txt
dockers:
  -
    binaries:
      - http-server
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.releaser
    image_templates:
      - "libsv/bitcoin-hc:latest"
      - "libsv/bitcoin-hc:{{ .Tag }}"
    extra_files:
      - data/sqlite/migrations/
release:
  name_template: "Release v{{.Version}}"
snapshot:
  name_template: "{{ .Tag }}-next"
