version: '3.7'

services:
  headers-client:
    container_name: headers-client
    image: libsv/bitcoin-hc:latest
    ports:
      - "8442:8442"
    environment:
      - DB_DSN=file:/data/blockheaders.db?_foreign_keys=true&pooled=true;
      - DB_SCHEMA_PATH=/migrations
    restart: unless-stopped
    volumes:
      - ~/data/headers-client:/data
    networks:
      - regtest-stack

networks:
  regtest-stack:
    name: regtest-stack
