version: '3.8'

services:
  headers-client:
    environment:
      - DB_DSN=user=postgres password=root dbname=spvheaders sslmode=disable host=host.docker.internal port=15433
      - DB_SCHEMA_PATH=/migrations
      - DB_TYPE=postgres
    depends_on:
      hc_postgres:
        condition: service_healthy

  hc_postgres:
    container_name: hc_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spvheaders
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 15433:5432
    restart: unless-stopped
    command: postgres -c 'max_connections=1000'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - headers-client-network

volumes:
  postgres-data: